# Generated by Django 5.2.4 on 2025-07-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='JXrODYA4RW9leNClnToAp8Q8qgdsgTU4', editable=False, max_length=32, unique=True),
        ),
    ]
